# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-extractcoding-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # TODO nf-core: Add required software dependencies here
  - bioconda::fastqc=0.11.8
  - bioconda::multiqc=1.7
  - conda-forge::r-markdown=1.1
  - conda-forge::r-base=3.6.1
  - bioconda::khmer=3.0.0a
  - conda-forge::gxx_linux-64
  - pip
  - pip:
    # Latest  olgabot/encodings--long-reads commit, manually written to
    # force rebuilding docker image
    - git+https://github.com/czbiohub/kh-tools.git@0466ecf#egg=khtools
